spring.application.name=auth-service
server.port=8082

jwt.secret=sample_secret_key_sample_32_char
jwt.expiration=86400

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5436/auth_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
