# Database Connection
#spring.datasource.url=jdbc:postgresql://<address>:<port>/<database_name>
#spring.datasource.username=<database account username>
#spring.datasource.password=<database password>

# Uncomment the line below if you want to expose this service over the network
#server.address=0.0.0.0

# Uncomment the line below if you want to expose the service on specific port
#server.port=<port>