spring.application.name=discount-service
server.port=8086

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5438/discount_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=discount-service

#Springwolf
springwolf.docket.base-package=solutions.skydev.pos.discount_service.consumer,solutions.skydev.pos.discount_service.producer

springwolf.docket.info.title=${spring.application.name}
springwolf.docket.info.version=1.0.0

springwolf.docket.servers.kafka-server.protocol=kafka
springwolf.docket.servers.kafka-server.host=${kafka.bootstrap.servers:localhost:9092}
