spring.application.name=order-orchestrator-service
server.port=8083

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5434/order_orchestrator_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-orchestrator-service

#Springwolf
springwolf.docket.base-package=solutions.skydev.pos.order_service.consumer,solutions.skydev.pos.order_orchestrator_service.producer

springwolf.docket.info.title=${spring.application.name}
springwolf.docket.info.version=1.0.0

springwolf.docket.servers.kafka-server.protocol=kafka
springwolf.docket.servers.kafka-server.host=${kafka.bootstrap.servers:localhost:9092}
